/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.ui;
import de.tud.omazan.ejb.CustomerEntityFacadeRemote;
import de.tud.omazan.ejb.ProductEntityFacadeRemote;
import javax.swing.*;

import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;

import javax.naming.InitialContext;
import javax.naming.NamingException;
import omazan.entities.CustomerEntity;
import omazan.entities.ProductEntity;

public class OmazanUI extends javax.swing.JFrame {
    @EJB
    private static ProductEntityFacadeRemote productEntityFacade;
    @EJB
    private static CustomerEntityFacadeRemote customerEntityFacade;

	//Fix for serial version ID
	private static final long serialVersionUID = 1L;
        
	/*
     *  TODO: Call the method to initiate the components
    */
    public OmazanUI() {
        initComponents();
        /*
	*  TODO: Make Customer, product and Addedit panel visibility false
	 */
        pnlCustomerData.setVisible(false);
        pnlProductData.setVisible(false);
        pnlAddEdit.setVisible(false);
        pnlAddEditCustData.setVisible(false);
        pnlAddProdDetails.setVisible(false);
        pnlPurchase.setVisible(false);
        pnlShipmentPanel.setVisible(false);
		}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 //   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	 pnlPurchase = new javax.swing.JPanel();
         lblLabelPurchase = new javax.swing.JLabel();
         lblPID = new javax.swing.JLabel();
         txtPID = new javax.swing.JTextField();
         btnpurchasedprod = new javax.swing.JButton();
         lblPurchasedName = new javax.swing.JLabel();
         lblProductName = new javax.swing.JLabel();
       
         
         lblLabelDetailsProduct = new javax.swing.JLabel();
         jScrollPane1 = new javax.swing.JScrollPane();
         tableProduct = new javax.swing.JTable();
         jScrollPane2 = new javax.swing.JScrollPane();
         tableCustomer = new javax.swing.JTable();
         lblLabelDeatilsCust = new javax.swing.JLabel();
         lblCID= new javax.swing.JLabel();
         txtCID=new javax.swing.JTextField();
         
         lblShipmentDetails = new javax.swing.JLabel();
         lblShipmentID = new javax.swing.JLabel();
         lblShipmentStatus = new javax.swing.JLabel();
         txtShipmentID = new javax.swing.JTextField();
         cmbxShipmentStatus = new javax.swing.JComboBox();
         btnUpdateShipment = new javax.swing.JButton();
         btnCancelShipment = new javax.swing.JButton();
         pnlShipmentPanel=new javax.swing.JPanel();
         btnEditShipment=new javax.swing.JButton();

        pnlCustomerData = new javax.swing.JPanel();
        lblCustData = new javax.swing.JLabel();
        lblCustID = new javax.swing.JLabel();
        lblCustName = new javax.swing.JLabel();
        txtCustID = new javax.swing.JTextField();
        txtCustName = new javax.swing.JTextField();
        btnCusAdd = new javax.swing.JButton();
        btnCustCancel = new javax.swing.JButton();
        pnlProductData = new javax.swing.JPanel();
      
        lblProdData = new javax.swing.JLabel();
        lblProdID = new javax.swing.JLabel();
        lblProdName = new javax.swing.JLabel();
        lblProdDesc = new javax.swing.JLabel();
        txtProdID = new javax.swing.JTextField();
        txtProdName = new javax.swing.JTextField();
        txtProdDesc = new javax.swing.JTextField();
        btnProdAdd = new javax.swing.JButton();
        btnProdCancel = new javax.swing.JButton();
        pnlWelcome = new javax.swing.JPanel();
        lblwelcome = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        rdbtnAdmin = new javax.swing.JRadioButton();
        rdbtnCustomer = new javax.swing.JRadioButton();
        pnlAddEdit = new javax.swing.JPanel();
        lblAddEdit = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        btnAddProd = new javax.swing.JButton();
        btnEditProd = new javax.swing.JButton();
        pnlAddProdDetails = new javax.swing.JPanel();
        lblAddProdDetails = new javax.swing.JLabel();
        lblNameProd = new javax.swing.JLabel();
        lblDescProd = new javax.swing.JLabel();
        txtNameProd = new javax.swing.JTextField();
        txtDescProd = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblIDGenerated = new javax.swing.JLabel();
        pnlAddEditCustData = new javax.swing.JPanel();
        lblAddEditData = new javax.swing.JLabel();
        btnAddCustomer = new javax.swing.JButton();
        btnEditCustomer = new javax.swing.JButton();
        btnGoBackCustomer = new javax.swing.JButton();
        pnlCustomerAdd = new javax.swing.JPanel();
        lblAddCustomer = new javax.swing.JLabel();
        lblNameCustomer = new javax.swing.JLabel();
        txtNameCustomer = new javax.swing.JTextField();
        btnAddCust = new javax.swing.JButton();
        btnCancelCust = new javax.swing.JButton();
        btnPurchase = new javax.swing.JButton();
        lblCustIDGenerated = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(374, 350));
        
        lblLabelPurchase.setText("Purchase Details");

        lblPID.setText("Product ID :");
        lblCID.setText("Customer ID :");

        btnpurchasedprod.setText("Purchase");

        lblPurchasedName.setText("Purchased Product :");
        
        lblLabelDetailsProduct.setText("Product Details");
        lblLabelDeatilsCust.setText("Customer Details");

        
        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Prod ID", "Prod Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProduct);
        
        tableCustomer.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String [] {
                    "Cust Name", "Prod Name", "Status"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
            jScrollPane2.setViewportView(tableCustomer);
                     

        lblProductName.setText("jLabel1");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        javax.swing.GroupLayout pnlPurchaseLayout = new javax.swing.GroupLayout(pnlPurchase);
        pnlPurchase.setLayout(pnlPurchaseLayout);
        pnlPurchaseLayout.setHorizontalGroup(
            pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPurchaseLayout.createSequentialGroup()
                .addGroup(pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPurchaseLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(lblLabelPurchase))
                    .addGroup(pnlPurchaseLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPurchaseLayout.createSequentialGroup()
                                .addComponent(lblPurchasedName)
                                .addGap(18, 18, 18)
                                .addComponent(lblProductName))
                            .addGroup(pnlPurchaseLayout.createSequentialGroup()
                                .addComponent(lblPID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                		.addGroup(pnlPurchaseLayout.createSequentialGroup()
                                                .addComponent(btnpurchasedprod, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnBack))
                                    .addComponent(txtPID))
                                    .addGap(18, 18, 18)
                                    .addComponent(lblCID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCID))
                                    .addGroup(pnlPurchaseLayout.createSequentialGroup()
                                .addComponent(lblPurchasedName)
                                .addGap(18, 18, 18)
                                .addComponent(lblProductName))
                            .addGroup(pnlPurchaseLayout.createSequentialGroup()
                                .addGroup(pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLabelDetailsProduct))
                                .addGap(18, 18, 18)
                                    .addGroup(pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblLabelDeatilsCust)))))) 
                    .addContainerGap(1141, Short.MAX_VALUE))
        );
        pnlPurchaseLayout.setVerticalGroup(
            pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPurchaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLabelPurchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPID)
                    .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCID)
                    .addComponent(txtCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpurchasedprod)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPurchasedName)
                    .addComponent(lblProductName))
                    .addGap(16, 16, 16)
                    .addGroup(pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabelDetailsProduct)
                     .addComponent(lblLabelDeatilsCust))
                    .addGap(18, 18, 18)
                    .addGroup(pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(255, Short.MAX_VALUE))
        );
        
        
        lblCustData.setText("Customer Details");

        lblCustID.setText("ID :");

        lblCustName.setText("Name :");

        btnCusAdd.setText("Update");
        
        btnBack.setText("Go Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnBackActionPerformed(evt);
            }

			private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
				pnlPurchase.setVisible(false);
				pnlCustomerAdd.setVisible(true);
				
			}
        });        

        btnCustCancel.setText("Cancel");
        btnCustCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustCancelActionPerformed(evt);
            }
        });
        
        /*Panel for editing customer data*/
        javax.swing.GroupLayout pnlCustomerDataLayout = new javax.swing.GroupLayout(pnlCustomerData);
        pnlCustomerData.setLayout(pnlCustomerDataLayout);
        pnlCustomerDataLayout.setHorizontalGroup(
            pnlCustomerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerDataLayout.createSequentialGroup()
                .addGroup(pnlCustomerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCustomerDataLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lblCustData))
                    .addGroup(pnlCustomerDataLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlCustomerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCustomerDataLayout.createSequentialGroup()
                                .addGroup(pnlCustomerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCustName)
                                    .addComponent(lblCustID))
                                .addGap(28, 28, 28)
                                .addGroup(pnlCustomerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCustID)
                                    .addComponent(txtCustName)))
                            .addGroup(pnlCustomerDataLayout.createSequentialGroup()
                                .addComponent(btnCusAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnCustCancel)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCustomerDataLayout.setVerticalGroup(
            pnlCustomerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCustData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustID)
                    .addComponent(txtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCustomerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustName)
                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCustomerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCusAdd)
                    .addComponent(btnCustCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblProdData.setText("Product Details");          

        lblProdID.setText("ID :");

        lblProdName.setText("Name :");

        lblProdDesc.setText("Description :");

        btnProdAdd.setText("Update");

        btnProdCancel.setText("Cancel");
        
        lblShipmentID.setText("Shipment ID :");

        lblShipmentStatus.setText("Shipment Status :");

        txtShipmentID.setText(" ");

        cmbxShipmentStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "packaging", "ontheway", "delivered", "cancelled" }));
                
        btnUpdateShipment.setText("Save");

        btnCancelShipment.setText("Cancel");  
        
        btnCancelShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnCancelShipmentActionPerformed(evt);
            }
        });
        
        
        btnProdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdCancelActionPerformed(evt);
            }
        });
        
        lblShipmentDetails.setText("Shipment Details");
        /*Panel for editing product data*/
        javax.swing.GroupLayout pnlProductDataLayout = new javax.swing.GroupLayout(pnlProductData);
        pnlProductData.setLayout(pnlProductDataLayout);
              
         
        pnlProductDataLayout.setHorizontalGroup(
	
            pnlProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductDataLayout.createSequentialGroup()
                .addGroup(pnlProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlProductDataLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblProdData))
                    .addGroup(pnlProductDataLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProductDataLayout.createSequentialGroup()
                                .addComponent(lblProdDesc)
                                .addGap(18, 18, 18)
                                .addComponent(txtProdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlProductDataLayout.createSequentialGroup()
                                .addComponent(btnProdAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnProdCancel))
                            .addGroup(pnlProductDataLayout.createSequentialGroup()
                                .addComponent(lblProdName)
                                .addGap(44, 44, 44)
                                .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlProductDataLayout.createSequentialGroup()
                                .addComponent(lblProdID)
                                .addGap(60, 60, 60)
                                .addComponent(txtProdID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pnlProductDataLayout.setVerticalGroup(
            pnlProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProdData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdID)
                    .addComponent(txtProdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdName)
                    .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdDesc)
                    .addComponent(txtProdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(pnlProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdAdd)
                    .addComponent(btnProdCancel))));

       pnlProductDataLayout.setVerticalGroup(
                pnlProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlProductDataLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblProdData)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblProdID)
                        .addComponent(txtProdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblProdName)
                        .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblProdDesc)
                        .addComponent(txtProdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                    .addGroup(pnlProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnProdAdd)
                        .addComponent(btnProdCancel)))
            );

        lblwelcome.setText("Welcome to Omazan!!");

        lblLogin.setText("Login As: ");

        rdbtnAdmin.setText("Admin/Employee");
        rdbtnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnAdminActionPerformed(evt);
            }
        });

        rdbtnCustomer.setText("Customer");
        rdbtnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnCustomerActionPerformed(evt);
            }
        });
        /*Panel for welcome Page*/
        javax.swing.GroupLayout pnlWelcomeLayout = new javax.swing.GroupLayout(pnlWelcome);
        pnlWelcome.setLayout(pnlWelcomeLayout);
        pnlWelcomeLayout.setHorizontalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblwelcome))
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblLogin)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnCustomer)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlWelcomeLayout.setVerticalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addComponent(lblwelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(rdbtnAdmin)
                    .addComponent(rdbtnCustomer)))
        );

        lblAddEdit.setText("Add/Edit Product Data");

        btnGoBack.setText("Go Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        btnAddProd.setText("Add");
        btnAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdActionPerformed(evt);
            }
        });
        
        btnEditShipment.setText("Shipment Details");
        btnEditShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnEditShipmentActionPerformed(evt);
            }
        });

        btnEditProd.setText("Edit");
        btnEditProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProdActionPerformed(evt);
            }
        });
        /*Panel to Add edit product data*/
        javax.swing.GroupLayout pnlAddEditLayout = new javax.swing.GroupLayout(pnlAddEdit);
        pnlAddEdit.setLayout(pnlAddEditLayout);
        pnlAddEditLayout.setHorizontalGroup(
            pnlAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddEditLayout.createSequentialGroup()
                .addGroup(pnlAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddEditLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblAddEdit))
                    .addGroup(pnlAddEditLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnAddProd)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditProd, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGoBack)
                        .addGap(18,18,18)
                        .addComponent(btnEditShipment)
                     		))
               .addContainerGap(136, Short.MAX_VALUE)));
   
   		//Panel for shipment details
		javax.swing.GroupLayout pnlShipmentPanelLayout = new javax.swing.GroupLayout(pnlShipmentPanel);
        pnlShipmentPanel.setLayout(pnlShipmentPanelLayout);
        pnlShipmentPanelLayout.setHorizontalGroup(
            pnlShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShipmentPanelLayout.createSequentialGroup()
                .addGroup(pnlShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlShipmentPanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lblShipmentDetails))
                    .addGroup(pnlShipmentPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pnlShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShipmentStatus)
                            .addComponent(lblShipmentID)
                            .addComponent(btnUpdateShipment))
                        .addGroup(pnlShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlShipmentPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addGroup(pnlShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtShipmentID, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(cmbxShipmentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlShipmentPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelShipment)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(151, 151, 151))
        );
        pnlShipmentPanelLayout.setVerticalGroup(
            pnlShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShipmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblShipmentDetails)
                .addGap(18, 18, 18)
                .addGroup(pnlShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShipmentID)
                    .addComponent(txtShipmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShipmentStatus)
                    .addComponent(cmbxShipmentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlShipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateShipment)
                    .addComponent(btnCancelShipment))
                .addContainerGap(33, Short.MAX_VALUE))
        );
 
        pnlAddEditLayout.setVerticalGroup(
            pnlAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAddEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProd)
                    .addComponent(btnEditProd)
                    .addComponent(btnGoBack)
                    .addComponent(btnEditShipment)
                          )
                .addGap(32, 32, 32))
        );

        lblAddProdDetails.setText("Add Product Details");

        lblNameProd.setText("Name :");

        lblDescProd.setText("Description :");

        btnAdd.setText("Add");
        
        btnCusAdd.addMouseListener(new MouseAdapter() { 
            public void mouseClicked(MouseEvent mouseEvent) {
                            InitialContext context;
                            try {
                                context = new InitialContext();
                                customerEntityFacade = (CustomerEntityFacadeRemote) context.lookup("java:global/OmazanApp/OmazanApp-ejb/CustomerEntityFacade");
                                CustomerEntity pe = new CustomerEntity();
                                System.out.println("Edit: Id of customer: "+txtCustID.getText());
                                pe.setId(Long.parseLong(txtCustID.getText()));
                                pe.setName(txtCustName.getText());
                                customerEntityFacade.edit(pe);
                            } catch (NamingException ex) {
                                Logger.getLogger(OmazanUI.class.getName()).log(Level.SEVERE, null, ex);
                            }
            }
        });
		
        /*Event generated on click of adding product*/
		btnProdAdd.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent mouseEvent) {
				/*
				 *  TODO: Insert Customer details into database
				 */
                            InitialContext context;
                            try {
                                context = new InitialContext();
                                productEntityFacade = (ProductEntityFacadeRemote) context.lookup("java:global/OmazanApp/OmazanApp-ejb/ProductEntityFacade");
                                ProductEntity pe = new ProductEntity();
                                System.out.println("Edit: Id of product: "+txtProdID.getText());
                                pe.setId(Long.parseLong(txtProdID.getText()));
                                pe.setName(txtProdName.getText());
                                productEntityFacade.edit(pe);
                            } catch (NamingException ex) {
                                Logger.getLogger(OmazanUI.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            
			}
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblIDGenerated.setText("ID of product : ");
        /*Panel to add product details*/
        javax.swing.GroupLayout pnlAddProdDetailsLayout = new javax.swing.GroupLayout(pnlAddProdDetails);
        pnlAddProdDetails.setLayout(pnlAddProdDetailsLayout);
        pnlAddProdDetailsLayout.setHorizontalGroup(
            pnlAddProdDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddProdDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAddProdDetails)
                .addGap(23, 23, 23))
            .addGroup(pnlAddProdDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddProdDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddProdDetailsLayout.createSequentialGroup()
                        .addComponent(lblNameProd)
                        .addGap(33, 33, 33)
                        .addComponent(txtNameProd))
                    .addGroup(pnlAddProdDetailsLayout.createSequentialGroup()
                        .addComponent(lblDescProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescProd))
                    .addGroup(pnlAddProdDetailsLayout.createSequentialGroup()
                        .addGroup(pnlAddProdDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddProdDetailsLayout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel))
                            .addComponent(lblIDGenerated))                    
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
                );
            
            
        pnlAddProdDetailsLayout.setVerticalGroup(
            pnlAddProdDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddProdDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddProdDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddProdDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameProd)
                    .addComponent(txtNameProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddProdDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescProd)
                    .addComponent(txtDescProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIDGenerated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddProdDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel)))               

             
        );

        lblAddEditData.setText("Add/Edit Customer Data");

        btnAddCustomer.setText("Add");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnEditCustomer.setText("Edit");
        btnEditCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCustomerActionPerformed(evt);
            }
        });

        btnGoBackCustomer.setText("Go back");
        btnGoBackCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackCustomerActionPerformed(evt);
            }
        });
        /*Panel to put buttons for add and edit customer data*/
        javax.swing.GroupLayout pnlAddEditCustDataLayout = new javax.swing.GroupLayout(pnlAddEditCustData);
        pnlAddEditCustData.setLayout(pnlAddEditCustDataLayout);
        pnlAddEditCustDataLayout.setHorizontalGroup(
            pnlAddEditCustDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddEditCustDataLayout.createSequentialGroup()
                .addGroup(pnlAddEditCustDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddEditCustDataLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblAddEditData))
                    .addGroup(pnlAddEditCustDataLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnAddCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(btnGoBackCustomer)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAddEditCustDataLayout.setVerticalGroup(
            pnlAddEditCustDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddEditCustDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddEditData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddEditCustDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCustomer)
                    .addComponent(btnEditCustomer)
                    .addComponent(btnGoBackCustomer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblAddCustomer.setText("Add Customer Details");

        lblNameCustomer.setText("Name :");

        btnAddCust.setText("Add");
        
		/*Event generated on click of add customer button */
		 btnAddCust.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent mouseEvent) {
				InitialContext context;
                         try {
				context = new InitialContext();
                                customerEntityFacade = (CustomerEntityFacadeRemote) context.lookup("java:global/OmazanApp/OmazanApp-ejb/CustomerEntityFacade");
                                CustomerEntity pe = new CustomerEntity();
                                System.out.println("Name of customer: "+txtNameCustomer.getText());
                                pe.setName(txtNameCustomer.getText());
                                customerEntityFacade.create(pe);
                         } catch (Exception e) {
                             
                         }

			}
        });
                 
                 btnEditProd.addMouseListener(new MouseAdapter() { 
                     public void mouseClicked(MouseEvent mouseEvent) {
                         InitialContext context;
                         try {
				context = new InitialContext();
                                productEntityFacade = (ProductEntityFacadeRemote) context.lookup("java:global/OmazanApp/OmazanApp-ejb/ProductEntityFacade");
                                ProductEntity pe = new ProductEntity();
                                System.out.println("Name of product: "+txtNameProd.getText());
                                pe.setId((Long.parseLong(txtProdID.getText())));
                                pe.setName(txtProdName.getText());
                                productEntityFacade.edit(pe);
                         } catch (Exception e) {
                             
                         }

			}
                 });

        btnCancelCust.setText("Cancel");
        btnCancelCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelCustActionPerformed(evt);
            }
        });

        btnPurchase.setText("Purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnPurchaseActionPerformed(evt);
            }

			private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {
				// TODO Auto-generated method stub
				pnlPurchase.setVisible(true);
				pnlCustomerAdd.setVisible(false);
				
				
				
			}
        });

        lblCustIDGenerated.setText("ID is : ");
        /*Panel for editing customer details*/
        javax.swing.GroupLayout pnlCustomerAddLayout = new javax.swing.GroupLayout(pnlCustomerAdd);
        pnlCustomerAdd.setLayout(pnlCustomerAddLayout);
        pnlCustomerAddLayout.setHorizontalGroup(
            pnlCustomerAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerAddLayout.createSequentialGroup()
                .addGroup(pnlCustomerAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCustomerAddLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblAddCustomer))
                    .addGroup(pnlCustomerAddLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pnlCustomerAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCustomerAddLayout.createSequentialGroup()
                                .addComponent(btnAddCust)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelCust)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPurchase))
                            .addGroup(pnlCustomerAddLayout.createSequentialGroup()
                                .addComponent(lblNameCustomer)
                                .addGap(18, 18, 18)
                                .addComponent(txtNameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCustIDGenerated))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlCustomerAddLayout.setVerticalGroup(
            pnlCustomerAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCustomerAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameCustomer)
                    .addComponent(txtNameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCustIDGenerated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCustomerAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCust)
                    .addComponent(btnCancelCust)
                    .addComponent(btnPurchase))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

       
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlAddEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlAddEditCustData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnlCustomerData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(pnlProductData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(pnlAddProdDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlCustomerAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
                
                .addGroup(layout.createSequentialGroup().addContainerGap()
                .addComponent(pnlPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                
                 .addGroup(layout.createSequentialGroup()
                .addComponent(pnlShipmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pnlAddEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAddEditCustData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCustomerData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCustomerAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                
                .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
                
                .addGroup(layout.createSequentialGroup()
                .addComponent(pnlShipmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 191, Short.MAX_VALUE))
                
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlProductData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAddProdDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        
        

        pack();
    }// </editor-fold>                        

    protected void btnCancelShipmentActionPerformed(ActionEvent evt) {
		// Method called on canceling shipment
    	pnlShipmentPanel.setVisible(false);
    	pnlAddEdit.setVisible(true);
		
	}

	protected void btnEditShipmentActionPerformed(java.awt.event.ActionEvent evt) {
		// Method to pop the shipment details panel
		pnlAddEdit.setVisible(false);
		pnlShipmentPanel.setVisible(true);
	}

	private void btnCustCancelActionPerformed(java.awt.event.ActionEvent evt) {                                              
        /*Action performed on click of cancel*/
        txtCustID.setText("");
        txtCustName.setText("");
        //txtCustproduct.setText("");
        pnlAddEditCustData.setVisible(true);
        pnlCustomerData.setVisible(false);
        
    }                                             

    private void rdbtnAdminActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        pnlAddEdit.setVisible(true);
        pnlWelcome.setVisible(false);
        pnlAddProdDetails.setVisible(false);
        pnlCustomerAdd.setVisible(false);
    }                                          

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        pnlAddEdit.setVisible(false);
        pnlWelcome.setVisible(true);
    }                                         

    private void btnProdCancelActionPerformed(java.awt.event.ActionEvent evt) {                                              
        /*Action performed on click of cancelling product details*/
        txtProdID.setText("");
        txtProdName.setText("");
        txtProdDesc.setText("");
        pnlAddEdit.setVisible(true);
        pnlProductData.setVisible(false);
        //rdbtbProductData.setEnabled(false);
        //rdbtnCustomerData.setEnabled(false);
    }                                             

    private void btnAddProdActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        pnlAddProdDetails.setVisible(true);
        pnlProductData.setVisible(false);
        pnlAddEdit.setVisible(false);
    }                                          

    private void btnEditProdActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        pnlProductData.setVisible(true);
        pnlAddProdDetails.setVisible(false);
        pnlAddEdit.setVisible(false);
    }                                           

    private void rdbtnCustomerActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        pnlAddEditCustData.setVisible(true);
        pnlWelcome.setVisible(false);
        pnlCustomerAdd.setVisible(false);
    }                                             

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        pnlCustomerAdd.setVisible(true);
        pnlCustomerData.setVisible(false);
        pnlAddEditCustData.setVisible(false);
    }                                              

    private void btnEditCustomerActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        pnlCustomerData.setVisible(true);
        pnlCustomerAdd.setVisible(false);
        pnlAddEditCustData.setVisible(false);
    }                                               

    private void btnGoBackCustomerActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        pnlWelcome.setVisible(true);
        pnlAddEditCustData.setVisible(false);
    }                                                 

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        pnlAddEdit.setVisible(true);
        pnlAddProdDetails.setVisible(false);
    }                                         

    private void btnCancelCustActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        pnlCustomerAdd.setVisible(false);
        pnlAddEditCustData.setVisible(true);
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OmazanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OmazanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OmazanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OmazanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OmazanUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify     
    private javax.swing.JButton btnpurchasedprod;
    private javax.swing.JLabel lblLabelPurchase;
    private javax.swing.JLabel lblPID;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblPurchasedName;
    private javax.swing.JPanel pnlPurchase;
    private javax.swing.JTextField txtPID;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddCust;
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnAddProd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelCust;
    private javax.swing.JButton btnCusAdd;
    private javax.swing.JButton btnCustCancel;
    private javax.swing.JButton btnEditCustomer;
    private javax.swing.JButton btnEditProd;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnGoBackCustomer;
    private javax.swing.JButton btnProdAdd;
    private javax.swing.JButton btnProdCancel;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JLabel lblAddCustomer;
    private javax.swing.JLabel lblAddEdit;
    private javax.swing.JLabel lblAddEditData;
    private javax.swing.JLabel lblAddProdDetails;
    private javax.swing.JLabel lblCustData;
    private javax.swing.JLabel lblCustID;
    private javax.swing.JLabel lblCustIDGenerated;
    private javax.swing.JLabel lblCustName;
    private javax.swing.JLabel lblDescProd;
    private javax.swing.JLabel lblIDGenerated;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNameCustomer;
    private javax.swing.JLabel lblNameProd;
    private javax.swing.JLabel lblProdData;
    private javax.swing.JLabel lblProdDesc;
    private javax.swing.JLabel lblProdID;
    private javax.swing.JLabel lblProdName;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JPanel pnlAddEdit;
    private javax.swing.JPanel pnlAddEditCustData;
    private javax.swing.JPanel pnlAddProdDetails;
    private javax.swing.JPanel pnlCustomerAdd;
    private javax.swing.JPanel pnlCustomerData;
    private javax.swing.JPanel pnlProductData;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JRadioButton rdbtnAdmin;
    private javax.swing.JRadioButton rdbtnCustomer;
    private javax.swing.JTextField txtCustID;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtDescProd;
    private javax.swing.JTextField txtNameCustomer;
    private javax.swing.JTextField txtNameProd;
    private javax.swing.JTextField txtProdDesc;
    private javax.swing.JTextField txtProdID;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTable tableProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLabelDetailsProduct;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLabelDeatilsCust;
    private javax.swing.JTable tableCustomer;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblCID;
    private javax.swing.JTextField txtCID;
    private javax.swing.JTextField txtShipmentID;
    private javax.swing.JLabel lblShipmentDetails;
    private javax.swing.JLabel lblShipmentID;
    private javax.swing.JLabel lblShipmentStatus;
    private javax.swing.JComboBox cmbxShipmentStatus;
    private javax.swing.JButton btnCancelShipment;
    private javax.swing.JButton btnUpdateShipment;
    private javax.swing.JPanel pnlShipmentPanel;
    private javax.swing.JButton btnEditShipment;
    // End of variables declaration      

}

  
  